-- -- Plugin Development
-- -- Set keymap for Current under development Plugin
-- vim.api.nvim_set_keymap('n', '<leader>ns', ':NeoSky<CR>', { noremap = true, silent = true })
--
-- -- Set keymap for Current under development Plugin
-- -- Set keymap for NeoSkyReload
-- vim.api.nvim_set_keymap('n', '<leader>nr', ':NeoSkyReload<CR>', { noremap = true, silent = true })
--
-- -- Set keymap for Current under development Plugin
-- vim.api.nvim_set_keymap('n', '<leader>nR', ':NeoSkyUpdate<CR>', { noremap = true, silent = true })
--
-- -- Set keymap for Current under development Plugin
-- vim.api.nvim_set_keymap('n', '<leader>nu', ':NeoSkyStart<CR>', { noremap = true, silent = true })
--
-- -- Set keymap for Current under development Plugin
-- vim.api.nvim_set_keymap('n', '<leader>nx', ':NeoSkyStop<CR>', { noremap = true, silent = true })

-- {
--   '3rd/image.nvim',
--   dependencies = { 'luarocks.nvim' },
--   opts = {
--     backend = 'ueberzug',
--     integrations = {
--       markdown = {
--         enabled = true,
--         clear_in_insert_mode = false,
--         download_remote_images = true,
--         only_render_image_at_cursor = false,
--         filetypes = { 'markdown', 'vimwiki' }, -- markdown extensions (ie. quarto) can go here
--       },
--       neorg = {
--         enabled = false,
--         clear_in_insert_mode = false,
--         download_remote_images = true,
--         only_render_image_at_cursor = false,
--         filetypes = { 'norg' },
--       },
--     },
--     max_width = nil,
--     max_height = nil,
--     max_width_window_percentage = nil,
--     max_height_window_percentage = 50,
--     tmux_show_only_in_active_window = true,
--     kitty_method = 'normal',
--   },
-- },
-- {
--   dir = '/home/sanhajio/development/pp/growth/nvim/neosky',
--   name = 'neosky',
-- },
return {}
